---
- name: Install rustup and friends
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path"
  args:
    warn: false
    creates: ~/.cargo/bin/rustup

- name: Source Rust configuration in zsh
  lineinfile:
    path: ~/.zshenv.local
    line: 'source "$HOME/.cargo/env"'
    create: yes
