---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - base
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=base dest=~/.playbook.provision mode=0644
