---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - c
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=build dest=~/.playbook.provision mode=0644
