---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - base
    - build
    - docker
    - desktop
    - mpd
    - emacs
    - games
    - gtk-flat
    - i3
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=full-desktop dest=~/.playbook.provision mode=0644
