#!/bin/bash
# curl -fL https://raw.githubusercontent.com/jws85/Dotfiles/master/provision | bash

command -v git >/dev/null 2>&1 || {
    echo "Installing git"
    sudo apt-get install git
}

HAVE_PIP=$( dpkg-query -W --showformat='${Status}\n' 'python3-pip' | grep "install ok installed" )
if [ "" == "$HAVE_PIP" ]; then
    echo "Installing pip"
    sudo apt-get install python3-pip
fi

HAVE_VENV=$( dpkg-query -W --showformat='${Status}\n' 'python3-venv' | grep "install ok installed" )
if [ "" == "$HAVE_VENV" ]; then
    echo "Installing python3-venv"
    sudo apt-get install python3-venv
fi

# Note that this is the Python 2.7 psutil!
HAVE_PSUTIL=$( dpkg-query -W --showformat='${Status}\n' 'python-psutil' | grep "install ok installed" )
if [ "" == "$HAVE_PSUTIL" ]; then
    echo "Installing python-psutil"
    sudo apt-get install python-psutil
fi

command -v pipx >/dev/null 2>&1 || {
    echo "Installing pipx"
    python3 -m pip install --user pipx
    python3 -m pipx ensurepath
}

# to reflect pipx being installed
source $HOME/.bashrc

command -v ansible >/dev/null 2>&1 || {
    echo "Installing ansible"
    pipx install ansible --include-deps
}

# Clone my dotfiles into ~/Dotfiles
if [ ! -d $HOME/Dotfiles ]; then
    echo "Downloading Dotfiles repo to ~/Dotfiles"
    cd $HOME
    git clone https://github.com/jws85/Dotfiles
    cd Dotfiles
else
    cd $HOME/Dotfiles
    git pull
fi

# Figure out which playbook to run
PLAYBOOK=base

if [ "server" == "$1" ]; then
    PLAYBOOK=server
elif [ "build" == "$1" ]; then
    PLAYBOOK=build
elif [ "php-build" == "$1" ]; then
    PLAYBOOK=php-build
elif [ "python-build" == "$1" ]; then
    PLAYBOOK=python-build
elif [ "min-desktop" == "$1" ]; then
    PLAYBOOK=min-desktop
elif [ "dev-desktop" == "$1" ]; then
    PLAYBOOK=dev-desktop
elif [ "full-desktop" == "$1" ]; then
    PLAYBOOK=full-desktop
fi

CONFIG=~/.playbook.provision
if [ -f $CONFIG ]; then
    PLAYBOOK=$( cat $CONFIG )
fi

# Provision it all
echo "Running playbook $PLAYBOOK!"

# I appreciate the attempt at levity ^_^ but I actually like the
# boring ol' defaults in terms of fitting stuff on my screen
export ANSIBLE_NOCOWS=1

ansible-playbook -i ~/Dotfiles/playbooks/inventory -K ~/Dotfiles/playbooks/$PLAYBOOK.yml
