# Ansible provisioning playbook
# Inspired by https://www.stavros.io/posts/provisioning-your-computer-one-command-awesome/

---
- name: Provision a machine
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  tasks:

  - name: Install prerequisites
    apt: name={{ item }}
    become: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker repository key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    become: yes

  - name: Add repositories
    apt_repository: repo='{{ item }}'
    register: ppa
    become: yes
    with_items:
      - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} nightly'

  - name: Update package cache
    apt: update_cache=yes
    become: yes
    when: ppa.changed

  - name: Install packages
    apt: name={{ item }}
    become: yes
    with_items:
      - build-essential
      - cowsay
      - figlet
      - fortunes
      - gdb
      - git
      - git-flow
      - htop
      - inxi
      - irssi
      - lolcat
      - minicom
      - php-cli
      - silversearcher-ag
      - sshfs
      - stow
      - tig
      - tmux
      - vim-nox
      - zsh

  - name: Install GUI applications
    apt: name={{ item }}
    become: yes
    with_items:
      - caja-dropbox
      - chromium-browser
      - clementine
      - emacs25-lucid
      - filezilla
      - firefox
      - gimp
      - git-gui
      - gitg
      - keepassx
      - remmina
      - rofi
      - sxiv
      - wireshark
      - vlc
      - zeal

  # You can use VDE to 'ease' network configuration of VMs on laptops.
  - name: Install KVM packages
    apt: name={{ item }}
    become: yes
    with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-bin
      - qemu-kvm
      - uml-utilities
      - vde2

  - name: Install Docker packages
    apt: name={{ item }}
    become: yes
    with_items:
      - docker-ce # Enabled by the Docker repository above

  # Hopefully there's never a problem with getcomposer.org :/
  - name: Install Composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    become: yes
    args:
      creates: /usr/local/bin/composer

  - name: Ensure directories exist
    file: path={{ item }} state=directory
    with_items:
      - ~/.local/bin
      - ~/.local/include
      - ~/.local/lib/pkgconfig
      - ~/.local/share/man
      - ~/.vim/autoload

  - name: Install youtube-dl
    get_url:
      url: https://yt-dl.org/downloads/latest/youtube-dl
      dest: ~/.local/bin/youtube-dl
      mode: a+rx

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.vim/autoload/plug.vim

  - name: Install gdbinit
    get_url:
      url: https://git.io/.gdbinit
      dest: ~/.gdbinit

  - name: Install antigen
    get_url:
      url: https://git.io/antigen
      dest: ~/.zsh/antigen.zsh

  - name: Clone emacs setup
    git:
      repo: https://github.com/jws85/.emacs.d.git
      dest: ~/.emacs.d/

  - name: Symlink dotfiles
    shell: stow -d ~/Dotfiles -t ~ {{ item }}
    with_items:
      - git
      - rofi
      - tmux
      - vim
      - xdefaults
      - zsh

  - name: Change shell to zsh
    become: yes
    user: name={{ ansible_user_id }} shell=/usr/bin/zsh groups=dialout,disk append=yes

  - name: Set MATE settings
    dconf: key="/org/mate/{{ item.key }}" value={{ item.value }}
    loop:
      - { key: 'desktop/interface/monospace-font-name', value: "'PragmataPro Mono 10.5'" }
      - { key: 'panel/objects/workspaceswitcherapplet/prefs/display-all-workspaces', value: "true" }
      - { key: 'panel/objects/workspaceswitcherapplet/prefs/num-rows', value: "1" }
      - { key: 'marco/general/num-workspaces', value: "10" }
      - { key: 'panel/objects/clockapplet/prefs/format', value: "'24-hour'" }
      - { key: 'panel/objects/clockapplet/prefs/show-date', value: "true" }
      - { key: 'desktop/peripherals/keyboard/kbd/options', value: "['ctrl\tctrl:swapcaps', 'Compose key\tcompose:ralt']" }

  - name: Set MATE terminal settings
    dconf: key="/org/mate/terminal/profiles/default/{{ item.key }}" value={{ item.value }}
    loop:
      - { key: 'use-system-font', value: "true" }
      - { key: 'use-custom-default-size', value: "true" }
      - { key: 'default-show-menubar', value: "false" }
      - { key: 'default-size-columns', value: "100" }
      - { key: 'default-size-rows', value: "35" }
      - { key: 'use-theme-colors', value: "false" }
      - { key: 'background-color', value: "'#000000000000'" }
      - { key: 'foreground-color', value: "'#FFFFFFFFFFFF'" }
      - { key: 'background-type', value: "'transparent'" }
      - { key: 'background-darkness', value: "0.9" }
      - { key: 'scrollbar-position', value: "'hidden'" }
      - { key: 'scrollback-lines', value: "65535" }

  - name: Set MATE keybindings
    dconf: key="/org/mate/marco/global-keybindings/{{ item.key }}" value={{ item.value }}
    loop:
      # S-1..S-0: Switch to desktop 1..10
      - { key: 'switch-to-workspace-1', value: "'<Mod4>1'" }
      - { key: 'switch-to-workspace-2', value: "'<Mod4>2'" }
      - { key: 'switch-to-workspace-3', value: "'<Mod4>3'" }
      - { key: 'switch-to-workspace-4', value: "'<Mod4>4'" }
      - { key: 'switch-to-workspace-5', value: "'<Mod4>5'" }
      - { key: 'switch-to-workspace-6', value: "'<Mod4>6'" }
      - { key: 'switch-to-workspace-7', value: "'<Mod4>7'" }
      - { key: 'switch-to-workspace-8', value: "'<Mod4>8'" }
      - { key: 'switch-to-workspace-9', value: "'<Mod4>9'" }
      - { key: 'switch-to-workspace-10', value: "'<Mod4>0'" }

      # S-s-1..S-s-0: Move window to desktop 1..10
      - { key: 'move-to-workspace-1', value: "'<Shift><Mod4>exclam'" }
      - { key: 'move-to-workspace-2', value: "'<Shift><Mod4>at'" }
      - { key: 'move-to-workspace-3', value: "'<Shift><Mod4>numbersign'" }
      - { key: 'move-to-workspace-4', value: "'<Shift><Mod4>dollar'" }
      - { key: 'move-to-workspace-5', value: "'<Shift><Mod4>percent'" }
      - { key: 'move-to-workspace-6', value: "'<Shift><Mod4>asciicircum'" }
      - { key: 'move-to-workspace-7', value: "'<Shift><Mod4>ampersand'" }
      - { key: 'move-to-workspace-8', value: "'<Shift><Mod4>asterisk'" }
      - { key: 'move-to-workspace-9', value: "'<Shift><Mod4>parenleft'" }
      - { key: 'move-to-workspace-10', value: "'<Shift><Mod4>parenright'" }

      # S-Left/S-Right: Switch to desktop on left/right
      - { key: 'switch-to-workspace-left', value: "'<Mod4>Left'" }
      - { key: 'switch-to-workspace-right', value: "'<Mod4>Right'" }
      - { key: 'switch-to-workspace-up', value: "'<Mod4>Up'" }
      - { key: 'switch-to-workspace-down', value: "'<Mod4>Down'" }

      # S-s-Left/S-s-Right: Move window to desktop on left/right
      - { key: 'move-to-workspace-left', value: "'<Shift><Mod4>Left'" }
      - { key: 'move-to-workspace-right', value: "'<Shift><Mod4>Right'" }
      - { key: 'move-to-workspace-up', value: "'<Shift><Mod4>Up'" }
      - { key: 'move-to-workspace-down', value: "'<Shift><Mod4>Down'" }

      # S-Tab: Swap to most recently used desktop
      - { key: 'switch-to-workspace-prev', value: "'<Mod4>Tab'" }

  - name: Set MATE custom keybindings
    dconf: key="/org/mate/desktop/keybindings/{{ item.key }}" value={{ item.value }}
    loop:
      # S-RET: Terminal
      - { key: 'custom0/action', value: "'mate-terminal'" }
      - { key: 'custom0/binding', value: "'<Mod4>Return'" }
      - { key: 'custom0/name', value: "'Terminal'" }

      # S-SPC: Rofi (launcher)
      - { key: 'custom1/action', value: "'rofi -show run -display-run \">>> \"'" }
      - { key: 'custom1/binding', value: "'<Mod4>space'" }
      - { key: 'custom1/name', value: "'Rofi (Run)'" }

      # S-e: Emacs
      - { key: 'custom2/action', value: "'emacsclient -c -n --alternate-editor=\"\"'" }
      - { key: 'custom2/binding', value: "'<Mod4>e'" }
      - { key: 'custom2/name', value: "'Emacs Client'" }
