# Ansible provisioning playbook
# Inspired by https://www.stavros.io/posts/provisioning-your-computer-one-command-awesome/

---
- name: Provision a machine
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  tasks:

  - name: Install prerequisites
    apt: name={{ item }}
    become: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker repository key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    become: yes

  - name: Add repositories
    apt_repository: repo='{{ item }}'
    register: ppa
    become: yes
    with_items:
      - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} nightly'

  - name: Update package cache
    apt: update_cache=yes
    become: yes
    when: ppa.changed

  - name: Install packages
    apt: name={{ item }}
    become: yes
    with_items:
      - build-essential
      - cowsay
      - figlet
      - fortunes
      - gdb
      - git
      - git-flow
      - htop
      - inxi
      - irssi
      - lolcat
      - minicom
      - php-cli
      - silversearcher-ag
      - sshfs
      - stow
      - tig
      - tmux
      - vim-nox
      - zsh

  - name: Install GUI applications
    apt: name={{ item }}
    become: yes
    with_items:
      - caja-dropbox
      - chromium-browser
      - clementine
      - emacs25-lucid
      - filezilla
      - firefox
      - gimp
      - git-gui
      - gitg
      - keepassx
      - remmina
      - rofi
      - sxiv
      - wireshark
      - vlc
      - zeal

  # You can use VDE to 'ease' network configuration of VMs on laptops.
  - name: Install KVM packages
    apt: name={{ item }}
    become: yes
    with_items:
      - bridge-utils
      - cpu-checker
      - libvirt-bin
      - qemu-kvm
      - uml-utilities
      - vde2

  - name: Install Docker packages
    apt: name={{ item }}
    become: yes
    with_items:
      - docker-ce # Enabled by the Docker repository above

  # Hopefully there's never a problem with getcomposer.org :/
  - name: Install Composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    become: yes
    args:
      creates: /usr/local/bin/composer

  - name: Ensure directories exist
    file: path={{ item }} state=directory
    with_items:
      - ~/.local/bin
      - ~/.local/include
      - ~/.local/lib/pkgconfig
      - ~/.local/share/man
      - ~/.vim/autoload

  - name: Install youtube-dl
    get_url:
      url: https://yt-dl.org/downloads/latest/youtube-dl
      dest: ~/.local/bin/youtube-dl
      mode: a+rx

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.vim/autoload/plug.vim

  - name: Install gdbinit
    get_url:
      url: https://git.io/.gdbinit
      dest: ~/.gdbinit

  - name: Install antigen
    get_url:
      url: https://git.io/antigen
      dest: ~/.zsh/antigen.zsh

  - name: Clone emacs setup
    git:
      repo: https://github.com/jws85/.emacs.d.git
      dest: ~/.emacs.d/

  - name: Symlink dotfiles
    shell: stow -d ~/Dotfiles -t ~ {{ item }}
    with_items:
      - git
      - rofi
      - tmux
      - vim
      - xdefaults
      - zsh

  - name: MATE configuration
    shell: ~/Dotfiles/configure-mate.sh

  - name: Change shell to zsh
    become: yes
    user: name={{ ansible_user_id }} shell=/usr/bin/zsh groups=dialout,disk append=yes
