---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - base
    - docker
    - kvm
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=server dest=~/.playbook.provision mode=0644
