---
- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: yes
  with_items:
    - https://syncthing.net/release-key.txt

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: yes
  with_items:
    - 'deb https://apt.syncthing.net/ syncthing stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications via apt
  become: yes
  apt:
    name:
      - filezilla
      - firefox
      - fonts-firacode
      - fman
      - gimp
      - git-gui
      - gitg
      - keepassxc
      - mpv
      - oneko
      - peek
      - qalculate-gtk
      - redshift
      - remmina
      - sox # to generate white noise!
      - syncthing
      - syncthing-gtk
      - vim-gtk3 # to enable +clipboard in vim for kitty scrollback
      - webp
      - wireshark
      - xsel
      - zeal

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/fontconfig
    - ~/.config/mpv

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'mpv/input.conf', dest: '~/.config/mpv/input.conf' }

- name: Copy default config if needed
  copy:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    force: no
  loop:
    - { src: 'fontconfig/fonts.conf', dest: '~/.config/fontconfig/fonts.conf' }
