---
- name: Install GUI applications via apt
  become: true
  apt:
    name:
      - qutebrowser
      - qutebrowser-qtwebengine

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/qutebrowser/dracula
    - ~/.local/share/qutebrowser/userscripts

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'config.py', dest: '~/.config/qutebrowser/config.py' }
    - { src: 'dracula/draw.py', dest: '~/.config/qutebrowser/dracula/draw.py' }
    - { src: 'dracula/__init__.py', dest: '~/.config/qutebrowser/dracula/__init__.py' }
    - { src: 'dracula/readme.md', dest: '~/.config/qutebrowser/dracula/readme.md' }
    - { src: 'qute-keepassxc', dest: '~/.local/share/qutebrowser/userscripts/qute-keepassxc' }
    - { src: 'qute-org-roam', dest: '~/.local/share/qutebrowser/userscripts/qute-org-roam' }
