#!/bin/sh

mpd_status=$( mpc status )
lines=$( echo "$mpd_status" | wc | awk '{print $1}' )

case $BLOCK_BUTTON in
  1) mpc toggle > /dev/null 2>&1 ;; # left click, toggle play/pause
  3) mpc stop > /dev/null 2>&1 ;;   # right click, stop
esac

icon=""
if [ $lines -eq "1" ]; then
    echo "$icon stopped"
    exit
fi

playpause=$( echo "$mpd_status" | awk 'FNR==2{print $1}' )
if [ $playpause = "[playing]" ]; then
    icon=""
elif [ $playpause = "[paused]" ]; then
    icon=""
fi

song=$( echo "$mpd_status" | awk 'FNR==1' )

echo "$icon $song"
echo "$icon $song"
