---
- name: Add libretro repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3B2BA0B6750986899B189AFF18DAAE7FECA3745F
  become: yes

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'ppa:libretro/stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install games via apt
  become: yes
  apt:
    name:
      - libretro-2048
      - libretro-bsnes-balanced
      - libretro-bsnes-performance
      - libretro-genesisplusgx
      - libretro-gambatte
      - libretro-mgba
      - libretro-mupen64plus
      - libretro-nestopia
      - nethack-console
      - retroarch
