# Settings for GNOME 3 as available in Pop_OS 20.04
#
# To get dconf settings:
#  1) run "dconf watch /" in a terminal
#  2) change the setting "normally"
#  3) see what got changed
---
- name: Install GNOME packages
  become: yes
  apt:
    name:
      - gnome-tweak-tool
      - gnome-shell-pomodoro

- name: Set fman as default file manager
  become: no
  shell: xdg-mime default fman.desktop inode/directory application/x-gnome-saved-search
  args:
    warn: no

- name: Update desktop database
  become: no
  shell: update-desktop-database ~/.local/share/applications/
  args:
    warn: no

- name: Keyboard customization
  dconf: key='/org/gnome/desktop/input-sources/xkb-options' value="['ctrl:swapcaps', 'compose:ralt']"

- name: Show day of the week on clock
  dconf: key='/org/gnome/desktop/interface/clock-show-weekday' value="true"

- name: Use 24-hour clock
  dconf: key={{ item }} value="'24h'"
  loop:
    - '/org/gnome/desktop/interface/clock-format'
    - '/org/gtk/settings/file-chooser/clock-format'

- name: Enable night time yellow filter
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/{ item.key }}"
    value: "{{ item.value }}"
  loop:
    # S-RET: Terminal
    - { key: 'night-light-enabled', value: "true" }
    - { key: 'night-light-schedule-automatic', value: "true" }
    - { key: 'night-light-temperature', value: "uint32 3700" }

- name: Set Super-period to toggle window stickiness
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-on-all-workspaces"
    value: "['<Super>period']"

- name: Set Super-semicolon to open terminal
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    # S-RET: Terminal
    - { key: 'custom0/command', value: "'kitty'" }
    - { key: 'custom0/binding', value: "'<Super>semicolon'" }
    - { key: 'custom0/name', value: "'Terminal'" }

- name: Set Super-PrtSc to open flameshot
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    # S-PrtSc: Flameshot
    - { key: 'custom1/command', value: "'flameshot gui'" }
    - { key: 'custom1/binding', value: "'<Super>Print'" }
    - { key: 'custom1/name', value: "'Screenshot with Flameshot'" }

- name: Add all of my custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
