# Settings for GNOME 3 as available in Pop_OS 20.04
#
# To get dconf settings:
#  1) run "dconf watch /" in a terminal
#  2) change the setting "normally"
#  3) see what got changed
---
- name: Install GNOME packages
  become: yes
  apt:
    name:
      - gnome-tweak-tool
      - gnome-shell-pomodoro

- name: Set fman as default file manager
  become: no
  shell: xdg-mime default fman.desktop inode/directory application/x-gnome-saved-search
  args:
    warn: no

- name: Update desktop database
  become: no
  shell: update-desktop-database ~/.local/share/applications/
  args:
    warn: no

- name: Keyboard customization
  dconf: key='/org/gnome/desktop/input-sources/xkb-options' value="['ctrl:swapcaps', 'compose:ralt']"

- name: Show day of the week on clock
  dconf: key='/org/gnome/desktop/interface/clock-show-weekday' value="true"

- name: Use 24-hour clock
  dconf: key={{ item }} value="'24h'"
  loop:
    - '/org/gnome/desktop/interface/clock-format'
    - '/org/gtk/settings/file-chooser/clock-format'

- name: Enable night time yellow filter
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'night-light-enabled', value: "true" }
    - { key: 'night-light-schedule-automatic', value: "true" }
    - { key: 'night-light-temperature', value: "uint32 3700" }

- name: Set Super-period to toggle window stickiness
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-on-all-workspaces"
    value: "['<Super>period']"

- name: Unset PrtSc button
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: "@as []"

- name: Unset "focus active notification" Super-n binding
  dconf:
    key: "/org/gnome/shell/keybindings/focus-active-notification"
    value: "@as []"

- name: Set Super-p to move workspace up
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-up"
    value: "['<Primary><Super>Up', '<Primary><Super>k', '<Super>p']"

- name: Set Super-Shift-p to move window up a workspace
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/pop-workspace-up"
    value: "['<Shift><Super>Up', '<Shift><Super>k', '<Shift><Super>p']"

- name: Set Super-n to move workspace down
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down"
    value: "['<Primary><Super>Down', '<Primary><Super>j', '<Super>n']"

- name: Set Super-Shift-n to move window down a workspace
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/pop-workspace-down"
    value: "['<Shift><Super>Down', '<Shift><Super>j', '<Shift><Super>n']"

- name: Set Super-semicolon to open terminal
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'custom0/command', value: "'kitty'" }
    - { key: 'custom0/binding', value: "'<Super>semicolon'" }
    - { key: 'custom0/name', value: "'Terminal'" }

- name: Use PrtSc to open gnome-screenshot interactively
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: 'custom1/command', value: "'gnome-screenshot -i'" }
    - { key: 'custom1/binding', value: "'Print'" }
    - { key: 'custom1/name', value: "'Screenshot'" }

- name: Add all of my custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
