# https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml

# Disable attempts to rescale font based on DPI
# q.v. https://github.com/alacritty/alacritty/issues/1501
env:
  WINIT_X11_SCALE_FACTOR: '1.0'

import:
  - /home/jws/.config/alacritty/dracula.yml

window:
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 5

font:
  size: 11.0
  normal:
    family: monospace

background_opacity: 0.95

selection:
  save_to_clipboard: true
