---
- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: true
  with_items:
    - 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xd89c66d0e31fea2874ebd20561922ab60068fcd6'

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: true
  with_items:
    - 'ppa:phoerious/keepassxc'

- name: Update package cache
  apt: update_cache=true
  become: true
  when: ppa.changed

- name: Install GUI applications via apt
  become: true
  apt:
    name:
      - keepassxc
