---
- name: Install MPD applications
  become: yes
  apt:
    name:
      - mpd
      - mpdris2
      - mpc
      - ncmpcpp
      - cantata

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.config/mpd
    - ~/.mpd/playlists
    - ~/.ncmpcpp

# MPD's config must exist before starting the daemon
- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'mpd.conf', dest: '~/.config/mpd/mpd.conf' }
    - { src: 'ncmpcpp/bindings', dest: '~/.ncmpcpp/bindings' }
    - { src: 'ncmpcpp/config', dest: '~/.ncmpcpp/config' }

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no

- name: Enable user MPD daemon
  systemd:
    name: mpd
    state: started
    enabled: yes
    scope: user
