---
- name: Add Ubuntu PPA repository keys
  apt_key: keyserver=keyserver.ubuntu.com id='{{ item }}'
  become: yes
  with_items:
    - 873503A090750CDAEB0754D93FF0E01EEAAFC9CD # ppa:kelleyk/emacs
    - 9CFAF7EB # fman
    - 2A8CB607A1D3332C18E86652B2732D4240C9212C # ppa:mmstick76/alacritty

- name: Add other repository keys
  apt_key: state=present url='{{ item }}'
  become: yes
  with_items:
    - https://repo.vivaldi.com/stable/linux_signing_key.pub
    - https://syncthing.net/release-key.txt
    - https://download.opensuse.org/repositories/home:kozec/xUbuntu_18.04/Release.key # syncthing-gtk

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'ppa:kelleyk/emacs'
    - 'ppa:mmstick76/alacritty'
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'
    - 'deb http://repo.vivaldi.com/stable/deb/ stable main'
    - 'deb https://apt.syncthing.net/ syncthing stable'
    - 'deb http://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.04/ /'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications via apt
  apt: name={{ item }}
  become: yes
  with_items:
    - alacritty
    - emacs26
    - feh
    - filezilla
    - firefox
    - flameshot
    - fman
    - gimp
    - git-gui
    - gitg
    - keepassx
    - mpv
    - qalculate-gtk
    - redshift-gtk
    - remmina
    - rofi
    - python3-qtpy # for em
    - scrot
    - syncthing
    - syncthing-gtk
    - tilda
    - vivaldi-stable
    - wireshark
    - xsel
    - zeal

- name: Install MPD applications
  apt: name={{ item }}
  become: yes
  with_items:
    - mpd
    - mpc
    - ncmpcpp
    - cantata

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no
- name: Enable user MPD daemon
  systemd:
    name: mpd
    state: started
    enabled: yes
    user: yes # deprecated as of 2.7

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - fman
    - mpd
    - redshift
    - rofi

# [FIXME] Tilda writes a regular file on top of the symlink on close,
# so I can't stow it, so annoying!!!!!!!
- name: Copy tilda configuration file
  copy:
    src: ~/Dotfiles/tilda/.config/tilda/config_0
    dest: ~/.config/tilda/config_0

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists

- name: Download em client
  git:
    repo: https://github.com/jws85/em
    dest: ~/.local/source/em
    update: no

- name: Install em client
  make:
    chdir: ~/.local/source/em
    target: install
    params:
      PREFIX: ~/.local
