---
- name: Add repository keys by ID
  apt_key: keyserver=keyserver.ubuntu.com id='{{ item }}'
  become: yes
  with_items:
    - 9CFAF7EB # fman

- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: yes
  with_items:
    - https://syncthing.net/release-key.txt

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: yes
  with_items:
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'
    - 'deb https://apt.syncthing.net/ syncthing stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications via apt
  become: yes
  apt:
    name:
      - alacritty
      - filezilla
      - firefox
      - flameshot
      - fman
      - gimp
      - git-gui
      - gitg
      - keepassxc
      - mpv
      - oneko
      - qalculate-gtk
      - remmina
      - sox # to generate white noise!
      - syncthing
      - syncthing-gtk
      - webp
      - wireshark
      - xsel
      - zeal

# MPD's config must exist before starting the daemon
- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - alacritty
    - fman
