---
- name: Add Nextcloud repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469
  become: yes

- name: Add fman repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9CFAF7EB
  become: yes

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'ppa:nextcloud-devs/client'
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications
  apt: name={{ item }}
  become: yes
  with_items:
    - caja-dropbox
    - chromium-browser
    - emacs25-lucid
    - feh
    - filezilla
    - firefox
    - flameshot
    - fman
    - gimp
    - git-gui
    - gitg
    - keepassx
    - nextcloud-client-caja
    - qalculate-gtk
    - redshift-gtk
    - remmina
    - rofi
    - scrot
    - wireshark
    - vlc
    - xsel
    - zeal

- name: Install MPD applications
  apt: name={{ item }}
  become: yes
  with_items:
    - mpd
    - mpc
    - cantata

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - mpd
    - redshift
    - rofi

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists
