---
- name: Add repository keys by ID
  apt_key: keyserver=keyserver.ubuntu.com id='{{ item }}'
  become: yes
  with_items:
    - 9CFAF7EB # fman

- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: yes
  with_items:
    # ubuntu-elisp ppa
    - 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0d7bae435adbc6c3e4918a74062d648fd62fce72'
    - https://syncthing.net/release-key.txt

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'ppa:ubuntu-elisp/ppa'
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'
    - 'deb https://apt.syncthing.net/ syncthing stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications via apt
  become: yes
  apt:
    name:
      - alacritty
      - autocutsel
      - emacs-snapshot
      - feh
      - filezilla
      - firefox
      - flameshot
      - fman
      - fonts-firacode
      - gimp
      - git-gui
      - gitg
      - keepassx
      - keynav
      - mpv
      - oneko
      - qalculate-gtk
      - redshift-gtk
      - remmina
      - rofi
      - scrot
      - sqlite3 # for org-roam in emacs
      - syncthing
      - syncthing-gtk
      - tilda
      - unclutter
      - wireshark
      - xsel
      - zeal

- name: Install MPD applications
  become: yes
  apt:
    name:
      - mpd
      - mpc
      - ncmpcpp
      - cantata

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no
- name: Enable user MPD daemon
  systemd:
    name: mpd
    state: started
    enabled: yes
    scope: user

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - alacritty
    - fman
    - mpd
    - redshift
    - rofi

# [FIXME] Tilda writes a regular file on top of the symlink on close,
# so I can't stow it, so annoying!!!!!!!
- name: Copy tilda configuration file
  copy:
    src: ~/Dotfiles/tilda/.config/tilda/config_0
    dest: ~/.config/tilda/config_0

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists

- name: Install em
  shell: pipx install git+https://github.com/jws85/em.git
  args:
    creates: ~/.local/bin/em
