---
- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic main'

- name: Install GUI applications
  apt: name={{ item }}
  become: yes
  with_items:
    - caja-dropbox
    - chromium-browser
    - emacs25-lucid
    - feh
    - filezilla
    - firefox
    - flameshot
    - gimp
    - git-gui
    - gitg
    - keepassx
    - nextcloud-client-caja
    - qalculate-gtk
    - redshift-gtk
    - remmina
    - rofi
    - scrot
    - wireshark
    - vlc
    - xsel
    - zeal

- name: Install MPD applications
  apt: name={{ item }}
  become: yes
  with_items:
    - mpd
    - mpc
    - cantata

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - mpd
    - redshift
    - rofi

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists
