---
- name: Add kelleyk emacs repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 873503A090750CDAEB0754D93FF0E01EEAAFC9CD
  become: yes

- name: Add Syncthing repository key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  become: yes

- name: Add fman repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9CFAF7EB
  become: yes

- name: Add Vivaldi repository key
  apt_key:
    url: https://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  become: yes

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'ppa:kelleyk/emacs'
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'
    - 'deb http://repo.vivaldi.com/stable/deb/ stable main'
    - 'deb https://apt.syncthing.net/ syncthing stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install GUI applications via apt
  apt: name={{ item }}
  become: yes
  with_items:
    - emacs26
    - feh
    - filezilla
    - firefox
    - flameshot
    - fman
    - gimp
    - git-gui
    - gitg
    - keepassx
    - mpv
    - qalculate-gtk
    - redshift-gtk
    - remmina
    - rofi
    - python3-qtpy # for em
    - scrot
    - syncthing
    - tilda
    - vivaldi-stable
    - wireshark
    - xsel
    - zeal

- name: Install MPD applications
  apt: name={{ item }}
  become: yes
  with_items:
    - mpd
    - mpc
    - cantata

# [FIXME] The ansible "snap" command isn't available until 2.8...
- name: Install Visual Studio Code
  become: yes
  shell: snap install --classic code

- name: Install Visual Studio packages
  shell: code --install-extension {{ item }}
  with_items:
    - Equinusocio.vsc-material-theme

# [FIXME] The ansible "snap" command isn't available until 2.8...
- name: Install GUI applications via snap
  become: yes
  shell: snap install {{ item }}
  with_items:
    - insomnia

# I prefer to run MPD against my music dir, as my user
- name: Disable system MPD daemon
  become: yes
  systemd:
    name: mpd
    state: stopped
    enabled: no

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - fman
    - mpd
    - redshift
    - rofi
    - vscode

# [FIXME] Tilda writes a regular file on top of the symlink on close,
# so I can't stow it, so annoying!!!!!!!
- name: Copy tilda configuration file
  copy:
    src: ~/Dotfiles/tilda/.config/tilda/config_0
    dest: ~/.config/tilda/config_0

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists

- name: Download em client
  git:
    repo: https://github.com/jws85/em
    dest: ~/.local/source/em
    update: no

- name: Install em client
  make:
    chdir: ~/.local/source/em
    target: install
    params:
      PREFIX: ~/.local
