---
- name: Install GUI applications
  apt: name={{ item }}
  become: yes
  with_items:
    - caja-dropbox
    - chromium-browser
    - emacs25-lucid
    - feh
    - filezilla
    - firefox
    - gimp
    - git-gui
    - gitg
    - keepassx
    - qalculate-gtk
    - redshift-gtk
    - remmina
    - rofi
    - scrot
    - wireshark
    - vlc
    - xsel
    - zeal

- name: Install MPD applications
  apt: name={{ item }}
  become: yes
  with_items:
    - mpd
    - mpc
    - cantata

- name: Symlink GUI application dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - mpd
    - redshift
    - rofi

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.mpd/playlists
