# https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml

env:
  # Truecolor support with tmux
  # https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
  TERM: 'xterm-256color'

  # Disable attempts to rescale font based on DPI
  # q.v. https://github.com/alacritty/alacritty/issues/1501
  WINIT_X11_SCALE_FACTOR: '1.0'

import:
  - /home/jws/.config/alacritty/catppuchin.yml

window:
  dynamic_title: true
  gtk_theme_variant: dark
  opacity: 0.95

scrolling:
  history: 10000
  multiplier: 5

font:
  size: 11.0
  normal:
    family: monospace

hints:
 enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|telnet:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    command: xdg-open
    post_processing: true
    mouse:
      enabled: true
      mods: Control
    binding:
      key: U
      mods: Alt

selection:
  save_to_clipboard: true

key_bindings:
  - { key: Space, mods: Alt, mode: ~Search, action: ToggleViMode }
  - { key: Escape, mode: Vi|~Search, action: ToggleViMode }
  - { key: V, mods: Alt, action: Paste }
  - { key: J, mods: Alt, action: ScrollPageDown }
  - { key: K, mods: Alt, action: ScrollPageUp }
  - { key: Plus, mods: Alt, action: IncreaseFontSize }
  - { key: Minus, mods: Alt, action: DecreaseFontSize }
  - { key: Equals, mods: Alt, action: ResetFontSize }
