---
- name: Add repository keys by ID
  apt_key: keyserver=keyserver.ubuntu.com id='{{ item }}'
  become: true
  with_items:
    - 9CFAF7EB # fman

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: true
  with_items:
    - 'deb [arch=amd64] https://fman.io/updates/ubuntu/ stable main'

- name: Update package cache
  apt: update_cache=true
  become: true
  when: ppa.changed

- name: Install
  become: true
  apt:
    name:
      - fman

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/fman/Local
    - ~/.config/fman/Plugins/User/Settings

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'Dialogs.json', dest: '~/.config/fman/Local/Dialogs.json' }
    - { src: 'Settings/Apps (Linux).json', dest: '~/.config/fman/Plugins/User/Settings/Apps (Linux).json' }
    - { src: 'Settings/Core Settings (Linux).json', dest: '~/.config/fman/Plugins/User/Settings/Core Settings (Linux).json' }
    - { src: 'Settings/File Associations (Linux).json', dest: '~/.config/fman/Plugins/User/Settings/File Associations (Linux).json' }
    - { src: 'Settings/Key Bindings (Linux).json', dest: '~/.config/fman/Plugins/User/Settings/Key Bindings (Linux).json' }
