---
- name: Install i3 via apt
  become: yes
  apt:
    name:
      - autorandr
      - dunst
      - feh # wallpaper
      - flameshot
      - i3
      - i3blocks
      - jq  # helper scripts
      - lxappearance  # easy way to set GTK theme
      - rofi
      - scrot
      - udiskie
      - unclutter
      - xdotool # for rofimoji
      - xscreensaver
      - xscreensaver-data-extra
      - xscreensaver-gl-extra

- name: Ensure the Qt style copies from GTK
  lineinfile:
    path: ~/.profile
    regexp: '^export\s+QT_STYLE_OVERRIDE='
    line: 'export QT_STYLE_OVERRIDE=gtk2'

- name: Install rofimoji
  shell: pipx install git+https://github.com/fdw/rofimoji
  args:
    creates: ~/.local/bin/rofimoji

- name: Install torii
  shell: pipx install git+https://github.com/jws85/torii.git
  args:
    creates: ~/.local/bin/torii

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/dunst
    - ~/.config/i3
    - ~/.config/i3blocks
    - ~/.config/rofi

- name: Symlink i3 dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'xcompose', dest: '~/.XCompose' }
    - { src: 'xdefaults', dest: '~/.Xdefaults' }
    - { src: 'xinitrc', dest: '~/.xinitrc' }
    - { src: 'xinitrc', dest: '~/.xsession' }
    - { src: 'xscreensaver', dest: '~/.xscreensaver' }
    - { src: 'dunst/dunstrc', dest: '~/.config/dunst/dunstrc' }
    - { src: 'i3wm/config.template', dest: '~/.config/i3/config.template' }
    - { src: 'i3blocks/config', dest: '~/.config/i3blocks/config' }
    - { src: 'rofi/config.rasi', dest: '~/.config/rofi/config.rasi' }
    - { src: 'scripts/i3-empty', dest: '~/.local/bin/i3-empty' }
    - { src: 'scripts/i3-reload', dest: '~/.local/bin/i3-reload' }
    - { src: 'scripts/i3blocks-battery', dest: '~/.local/bin/i3blocks-battery' }
    - { src: 'scripts/i3blocks-cpu', dest: '~/.local/bin/i3blocks-cpu' }
    - { src: 'scripts/i3blocks-mpd', dest: '~/.local/bin/i3blocks-mpd' }
    - { src: 'scripts/i3blocks-pulseaudio', dest: '~/.local/bin/i3blocks-pulseaudio' }

- name: Copy default config if needed
  copy:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    force: no
  loop:
    - { src: 'i3wm/config.json', dest: '~/.config/i3/config.json' }
    - { src: 'defaultwall.jpg', dest: '~/.wallpaper' }

- name: Generate i3 config
  shell: i3-reload
  args:
    creates: ~/.config/i3/config

- name: Clone my helper scripts
  git:
    repo: https://github.com/jws85/scripts
    dest: ~/.local/source/scripts
    update: no

- name: Install helper scripts
  make:
    chdir: ~/.local/source/scripts
    target: install
    params:
      PREFIX: ~/.local
