---
- name: Disable Ubuntu's message-of-the-day
  copy:
    content: ''
    dest: ~/.hushlogin

- name: Install Apt prerequisites
  apt: name={{ item }}
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add mosh PPA key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F2923D3F37FEF230BDDC376E3EB9326A7BF6DFCD
  become: yes

- name: Add mosh PPA
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'deb http://ppa.launchpad.net/keithw/mosh/ubuntu {{ ansible_distribution_release }} main'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install packages
  apt: name={{ item }}
  become: yes
  with_items:
    - cowsay
    - cmatrix
    - figlet
    - fortunes
    - fping
    - f3
    - htop
    - inxi
    - iotop
    - iftop
    - iptraf
    - irssi
    - lolcat
    - minicom
    - mosh
    - nmap
    - openssh-server
    - silversearcher-ag
    - speedtest-cli
    - sshfs
    - stow
    - tig
    - tmux
    - vim-nox
    - zsh

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.local/bin
    - ~/.local/include
    - ~/.local/lib/pkgconfig
    - ~/.local/share/man
    - ~/.local/source
    - ~/.vim/autoload

- name: Symlink provisioning script
  file: src="~/Dotfiles/provision" dest="~/.local/bin/provision" state=link

- name: Install youtube-dl
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: ~/.local/bin/youtube-dl
    mode: a+rx

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Clone emacs setup
  git:
    repo: https://github.com/jws85/.emacs.d.git
    dest: ~/.emacs.d/
    update: no

- name: Clone zsh setup
  git:
    repo: https://github.com/jws85/prezto
    dest: ~/.zprezto/
    recursive: yes
    update: no

- name: Symlink zsh dotfiles
  file: src="~/.zprezto/runcoms/{{ item }}" dest="~/.{{ item }}" state=link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: Symlink dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - git
    - tmux
    - vim

- name: Change shell to zsh
  become: yes
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh groups=dialout,disk append=yes
