---
- name: Disable Ubuntu's message-of-the-day
  copy:
    content: ''
    dest: ~/.hushlogin

- name: Install Apt prerequisites
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Install packages
  become: yes
  apt:
    name:
      - cowsay
      - cmatrix
      - entr
      - figlet
      - fortunes
      - fping
      - f3
      - htop
      - inxi
      - iotop
      - iftop
      - iptraf
      - irssi
      - lolcat
      - minicom
      - mosh
      - nmap
      - openssh-server
      - renameutils
      - ripgrep
      - speedtest-cli
      - sshfs
      - stow
      - tig
      - tmux
      - neovim
      - zsh

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.local/bin
    - ~/.local/include
    - ~/.local/lib/pkgconfig
    - ~/.local/share/man
    - ~/.local/source
    - ~/.config/nvim/autoload

- name: Symlink provisioning script
  file: src="~/Dotfiles/provision" dest="~/.local/bin/provision" state=link

- name: Install youtube-dl
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: ~/.local/bin/youtube-dl
    mode: a+rx

- name: Clone emacs setup
  git:
    repo: https://github.com/jws85/.emacs.d.git
    dest: ~/.emacs.d/
    update: no

- name: Clone zsh setup
  git:
    repo: https://github.com/jws85/prezto
    dest: ~/.zprezto/
    recursive: yes
    update: no

- name: Symlink zsh dotfiles
  file: src="~/.zprezto/runcoms/{{ item }}" dest="~/.{{ item }}" state=link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
    - p10k.zsh

- name: Symlink dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - git
    - tmux
    - vim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
    mode: 0644

- name: Symlink tmux dotfile
  file: src='~/.tmux/tmux.conf' dest='~/.tmux.conf' state=link

- name: Change shell to zsh
  become: yes
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh groups=dialout,disk append=yes
