---
- name: Install packages
  become: true
  apt:
    name:
      - git
      - git-annex
      - git-flow

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'gitconfig', dest: '~/.gitconfig' }
