---
- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: true
  with_items:
    # ubuntu-elisp ppa
    - 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x873503a090750cdaeb0754d93ff0e01eeaafc9cd'

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: true
  with_items:
    - 'ppa:kelleyk/emacs'

- name: Update package cache
  apt: update_cache=true
  become: true
  when: ppa.changed

- name: Install emacs and associated packages
  become: true
  apt:
    name:
      - dvipng
      - emacs27
      - pandoc
      - python3-tk # for em
      - sqlite3 # for org-roam in emacs
      # say goodbye to about a gig of space
      - texlive
      - texlive-plain-generic

- name: Ensure directories exist
  file: path={{ item }} state=directory
  with_items:
    - ~/.local/share/applications

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'emacs.d', dest: '~/.emacs.d' }
    - { src: 'desktop/org-protocol.desktop', dest: '~/.local/share/applications/org-protocol.desktop' }

- name: Update file associations
  shell: update-desktop-database ~/.local/share/applications/

- name: Install em
  shell: pipx install git+https://github.com/jws85/em.git
  args:
    creates: ~/.local/bin/em
