---
- name: Install C packages
  become: yes
  apt:
    name:
      - build-essential
      - clangd
      - gdb
      - gnupg
      - pbuilder

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'gdbinit', dest: '~/.gdbinit' }
