---
- name: Install C packages
  become: true
  apt:
    name:
      - bear
      - build-essential
      - clang-format
      - clangd
      - gdb
      - gnupg
      - pbuilder

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'gdbinit', dest: '~/.gdbinit' }
