---
- name: Install golang
  become: true
  shell: "curl -L https://golang.org/dl/go1.15.8.linux-amd64.tar.gz | tar -C /usr/local -xzf -"
  args:
    warn: false
    creates: /usr/local/go/bin/go

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'go.fish', dest: '~/.config/fish/local/go.fish' }
