---
- name: Install golang
  become: true
  shell: "curl -L https://golang.org/dl/go1.15.8.linux-amd64.tar.gz | tar -C /usr/local -xzf -"
  args:
    warn: false
    creates: /usr/local/go/bin/go

- name: Load custom configuration in zsh
  lineinfile:
    path: ~/.zshenv.local
    line: 'source $HOME/Dotfiles/roles/go/files/go.zsh'
    create: yes

- name: Install gopls
  shell: "GO111MODULE=on go get golang.org/x/tools/gopls@latest"
  args:
    warn: false
    creates: ~/.config/go/bin/gopls

- name: Install guru
  shell: "go get golang.org/x/tools/cmd/guru"
  args:
    warn: false
    creates: ~/.config/go/bin/guru
