---
- name: Install golang
  become: true
  shell: "curl -L https://golang.org/dl/go1.15.8.linux-amd64.tar.gz | tar -C /usr/local -xzf -"
  args:
    warn: false
    creates: /usr/local/go/bin/go

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'go.fish', dest: '~/.config/fish/local/go.fish' }

- name: Install gopls
  shell: "GO111MODULE=on go get golang.org/x/tools/gopls@latest"
  args:
    warn: false
    creates: ~/.config/go/bin/gopls

- name: Install guru
  shell: "go get golang.org/x/tools/cmd/guru"
  args:
    warn: false
    creates: ~/.config/go/bin/guru
