---
- name: Install i3 via apt
  become: true
  apt:
    name:
      - rofi

- name: Install rofimoji
  shell: pipx install git+https://github.com/fdw/rofimoji
  args:
    creates: ~/.local/bin/rofimoji

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/rofi

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'config.rasi', dest: '~/.config/rofi/config.rasi' }
