---
- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: true
  with_items:
    - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: true
  with_items:
    - 'deb https://deb.nodesource.com/node_12.x focal main'

- name: Update package cache
  apt: update_cache=true
  become: true
  when: ppa.changed

- name: Install npm and node
  become: true
  apt:
    name:
      - nodejs

- name: Create Node global install directory
  file: path={{ item }} state=directory
  with_items:
    - ~/.npm-packages/

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'npmrc', dest: '~/.npmrc' }

- name: Load custom configuration in zsh
  lineinfile:
    path: ~/.zshenv.local
    line: 'source $HOME/Dotfiles/roles/node/files/node.zsh'
    create: yes

- name: Install typescript-language-server
  shell: npm install -g typescript-language-server
  args:
    creates: ~/.npm-packages/bin/typescript-language-server
    warn: false
