---
- name: Install i3 via apt
  apt: name={{ item }}
  become: yes
  with_items:
    - i3
    - i3blocks
    - udiskie
    - autorandr

- name: Symlink i3 dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - i3

- name: Copy default wallpaper
  copy: src=nasa-53884.jpg dest=~/.wallpaper force=no

- name: Clone my helper scripts
  git:
    repo: https://github.com/jws85/scripts
    dest: ~/.local/source/scripts
    update: no

- name: Install helper scripts
  make:
    chdir: ~/.local/source/scripts
    target: install
    params:
      PREFIX: ~/.local
