---
- name: Install i3 via apt
  apt: name={{ item }}
  become: yes
  with_items:
    - i3
    - i3blocks
    - udiskie
    - autorandr

- name: Symlink i3 dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - i3

- name: Copy default wallpaper
  copy: src=nasa-53884.jpg dest=~/.wallpaper force=no

- name: Copy default weather script
  become: yes
  copy: src=wttr.in dest=/etc/wttr.in/script.sh force=no

- name: Run weather script every fifteen minutes
  become: yes
  cron:
    name: "Run weather script every fifteen minutes"
    job: /etc/wttr.in/script.sh
    user: jws
    minute: "*/15"
