---
- name: Install i3 via apt
  apt: name={{ item }}
  become: yes
  with_items:
    - i3
    - i3blocks
    - udiskie

- name: Symlink i3 dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - i3
