---
- name: Install i3 via apt
  become: yes
  apt:
    name:
      - autorandr
      - dunst
      - flameshot
      - i3
      - i3blocks
      - jq  # helper scripts
      - rofi
      - scrot
      - udiskie
      - unclutter
      - xscreensaver
      - xscreensaver-data-extra
      - xscreensaver-gl-extra

- name: Install rofimoji
  shell: pipx install git+https://github.com/fdw/rofimoji
  args:
    creates: ~/.local/bin/rofimoji

- name: Install torii
  shell: pipx install git+https://github.com/jws85/torii.git
  args:
    creates: ~/.local/bin/torii

- name: Symlink i3 dotfiles
  shell: stow -d ~/Dotfiles -t ~ {{ item }}
  with_items:
    - i3
    - dunst

- name: Copy default config.json if needed
  copy: src=~/.config/i3/config.sample.json dest=~/.config/i3/config.json force=no

- name: Generate i3 config
  make:
    chdir: ~/.config/i3
    target: all

- name: Copy default wallpaper
  copy: src=defaultwall.jpg dest=~/.wallpaper force=no

- name: Clone my helper scripts
  git:
    repo: https://github.com/jws85/scripts
    dest: ~/.local/source/scripts
    update: no

- name: Install helper scripts
  make:
    chdir: ~/.local/source/scripts
    target: install
    params:
      PREFIX: ~/.local
