---
- name: Add Docker repository key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add repositories
  apt_repository: repo='{{ item }}'
  register: ppa
  become: yes
  with_items:
    - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install Docker packages
  become: yes
  apt:
    name:
      - docker-ce # Enabled by the Docker repository above
      - docker-compose

- name: Add jws user to docker group
  become: yes
  user:
    name: jws
    group: docker
    append: yes
