---
- name: Disable Ubuntu's message-of-the-day
  copy:
    content: ''
    dest: ~/.hushlogin

- name: Install Apt prerequisites
  become: yes
  apt:
    name:
      - apt-file
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Install packages
  become: yes
  apt:
    name:
      - at
      - cifs-utils
      - cowsay
      - cmatrix
      - diceware
      - dtach
      - entr
      - figlet
      - fish
      - fortunes
      - fping
      - fzf
      - f3
      - git
      - graphviz
      - htop
      - inxi
      - iotop
      - iftop
      - ipcalc
      - iptraf
      - irssi
      - lolcat
      - minicom
      - mosh
      - nmap
      - openssh-server
      - renameutils
      - ripgrep
      - speedtest-cli
      - sshfs
      - tig
      - vim

- name: Remove packages I don't want
  become: yes
  apt:
    name:
      # Removing because it updates Firefox from under me, causing infuriating
      # error messages:
      # https://askubuntu.com/questions/1279041/disabling-firefox-background-upgrades
      - unattended-upgrades
      # Removing because:
      #  - it clutters up df output
      #  - you can't change ~/snap to ~/Snap
      #  - flatpak is more open
      - snapd
    state: absent


- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.local/bin
    - ~/.local/include
    - ~/.local/lib/pkgconfig
    - ~/.local/share/man
    - ~/.local/source
    - ~/.config/fish
    - ~/.config/fish/local

- name: Symlink provisioning script
  file: src="~/Dotfiles/provision" dest="~/.local/bin/provision" state=link

- name: Install youtube-dl
  shell: pipx install youtube-dl
  args:
    creates: ~/.local/bin/youtube-dl

- name: Install bpytop
  shell: pipx install bpytop
  args:
    creates: ~/.local/bin/bpytop

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'digrc', dest: '~/.digrc' }
    - { src: 'gitconfig', dest: '~/.gitconfig' }
    - { src: 'vimrc', dest: '~/.vimrc' }
    - { src: 'fish/config.fish', dest: '~/.config/fish/config.fish' }
    - { src: 'fish/fish_plugins', dest: '~/.config/fish/fish_plugins' }

    - { src: 'scripts/bin2music', dest: '~/.local/bin/bin2music' }
    - { src: 'scripts/bowdler', dest: '~/.local/bin/bowdler' }
    - { src: 'scripts/noise', dest: '~/.local/bin/noise' }
    - { src: 'scripts/pdf2images', dest: '~/.local/bin/pdf2images' }
    - { src: 'scripts/permfix', dest: '~/.local/bin/permfix' }
    - { src: 'scripts/rocketpost', dest: '~/.local/bin/rocketpost' }
    - { src: 'scripts/setwall', dest: '~/.local/bin/setwall' }
    - { src: 'scripts/thanos', dest: '~/.local/bin/thanos' }

- name: Download, install, and update fisher
  shell: fish -c "curl -L git.io/fisher | source && fisher install" < ~/.config/fish/fish_plugins
  args:
    creates: ~/.config/fish/completions/fisher.fish

- name: Install Starship prompt command
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- -b $HOME/.local/bin -y
  args:
    creates: ~/.local/bin/starship
    warn: false

- name: Change shell to fish
  become: yes
  user: name={{ ansible_user_id }} shell=/usr/bin/fish groups=dialout,disk append=yes
