---
- name: Install PHP packages
  become: yes
  apt:
    name:
      - php-cli
      - php-xml

# Hopefully there's never a problem with getcomposer.org :/
- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  become: yes
  args:
    creates: /usr/local/bin/composer
    warn: false

# Requires NodeJS
- name: Install Intelephense
  shell: npm install -g intelephense
  args:
    creates: ~/.npm-packages/bin/intelephense
    warn: false

- name: Ensure directories exist
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.config/composer

- name: Symlink dotfiles
  file:
    src: "{{ role_path}}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: 'composer.json', dest: '~/.config/composer/composer.json' }
    - { src: 'composer.lock', dest: '~/.config/composer/composer.lock' }
    - { src: 'php.fish', dest: '~/.config/fish/local/php.fish' }

- name: Install PHP utilities via composer
  shell: composer global install
