---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - build
  post_tasks:
    - name: Create ~/.playbook.provision
      copy: content=build dest=~/.playbook.provision mode=644
