---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - build
    - docker
    - desktop
    - gnome
  post_tasks:
    - name: Create ~/.playbook.provision
      copy: content=dev-desktop dest=~/.playbook.provision mode=644
