---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - desktop
    - gnome
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=min-desktop dest=~/.playbook.provision mode=0644
