---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - c
    - node
    - python
  pre_tasks:
    - name: Create ~/.playbook.provision
      copy: content=python-build dest=~/.playbook.provision mode=0644
