---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - base
    - docker
    - kvm
  post_tasks:
    - name: Create ~/.playbook.provision
      copy: content=server dest=~/.playbook.provision mode=644
