---
- name: Add repository keys by URL
  apt_key: state=present url='{{ item }}'
  become: yes
  with_items:
    - https://syncthing.net/release-key.txt

- name: Add repositories
  apt_repository: repo='{{ item }}' mode=0644
  register: ppa
  become: yes
  with_items:
    - 'deb https://apt.syncthing.net/ syncthing stable'

- name: Update package cache
  apt: update_cache=yes
  become: yes
  when: ppa.changed

- name: Install
  become: yes
  apt:
    name:
      - syncthing
      - syncthing-gtk
