#!/usr/bin/env bash
# Moves to next *empty* workspace

command -v jq >/dev/null 2>&1 || { echo >&2 "Please install jq!"; exit 1; }

# Get the max numbered open workspace
NUMWK=$( i3-msg -t get_workspaces | jq 'map(.num) | max' )

# Add 1 to it
UNUSED=$(( $NUMWK + 1 ))

# If the first argument is 'move' move the current window to the new workspace
if [ "$1" == "move" ]; then
    i3-msg "move container to workspace number $UNUSED"
fi

# Move focus to the new workspace
i3-msg "workspace number $UNUSED"
