#!/bin/sh

case $BLOCK_BUTTON in
  1) pavol mute ;;  # left click, toggle mute
  3) pavol mute ;;  # right click, toggle mute
  4) pavol up   ;;  # scroll up, louder
  5) pavol down ;;  # scroll down, quieter
esac

muted=$( pavol is-muted )
if [ "$muted" = "no" ]; then
    printf ' %s%%' $( pavol current )
else
    echo " ---"
fi
